"""empty message

Revision ID: 8a8b961d057c
Revises: 906d5368b640
Create Date: 2020-04-05 20:53:14.539590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a8b961d057c'
down_revision = '906d5368b640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_pkey', 'Show', type_='primary')
    op.execute('alter table "Show" add column id serial primary key;')
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Show', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Show', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_primary_key('Show_pkey', 'Show', ['venue_id', 'artist_id']) 
    op.drop_column('Show', 'id')
    # ### end Alembic commands ###
